image: google/dart:latest

stages:
  - build
  - test

before_script:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  - export PATH=$(echo "${PATH}" | sed -Ee 's/(^|[\:])\/usr\/lib\/dart\/bin[\/]?([\:]|$)/:/; s/$/:\/usr\/lib\/dart\/bin/')
  - export PUB_CACHE="${PWD}/.pub_cache/"
  - dart --version
  - which dart2native
  - pub version
  - pub get
  - pub upgrade

build:
  stage: build
  script:
    - dart2native bin/main.dart -o doul

#test:
#  stage: test
#  script:
#    - pub run test
#  only:
#    - master
#  tags:
#    - docker
