name: xnx
version: 0.1.0
description: A command-line utility to eXpand text content aNd to eXecute external utilities.
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  collection: ^1.16.0
  intl: ^0.18.0
  json5: ^0.8.0
  json_path: ^0.4.1
  file: ^6.1.2
  glob: ^2.1.0
  meta: ^1.8.0
  path: ^1.8.2
  thin_logger: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
