name: xnx
version: 0.2.2
description: A command-line utility to eXpand text content aNd to eXecute external utilities.
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/xnx/

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  archive: ^3.3.7
  args: ^2.3.1
  collection: ^1.16.0
  intl: ^0.19.0
  json5: ^0.8.0
  json_path: ^0.7.1
  file: ^7.0.0
  glob: ^2.1.0
  meta: ^1.8.0
  path: ^1.8.2
  shell_cmd: ^0.2.7
  string_scanner: ^1.2.0
  thin_logger: ^0.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.4
