name: doul
description: Command-line utility to expand text content by placeholders and to run external utilities.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  archive: ^2.0.13
  args: ^1.5.3
  glob: ^1.2.0
  path: ^1.6.4
  process_run: ^0.10.7

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
