name: xnx
version: 0.1.0
description: A command-line utility to eXpand text content aNd to eXecute external utilities.
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  archive: ^3.1.6
  args: ^2.0.0
  intl: ^0.17.0
  json5: ^0.6.1
  json_path: ^0.3.0
  file: ^6.0.0
  glob: ^2.0.0
  path: ^1.6.4
  process_run: ^0.12.1+1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.6.0
