#!/bin/bash

################################################################################

function realpath() { # macOS does not have such utility out of the box
  local old="${PWD}"

  cd $(dirname "${1}") &&\
  echo "${PWD}/$(basename "${1}")" &&\
  cd "${old}"
}

################################################################################

if (( ${#} != 1 )); then
  cat <<EOT >&2

USAGE: $(basename "${0}") <out>

<out> is target MS Office file (docx, xlsx, pptx, etc.)
source files are taken from directory <out>.dir

EOT
  exit 1
fi

################################################################################

OUT=$(realpath "${1}")
DIR="${OUT}.dir"

cd "${DIR}" &&\
zip -m -r "${OUT}" . &&\
cd .. &&\
rmdir "${DIR}" &&\
exit 0

exit 1

################################################################################
