#!/bin/bash

function realpath() { # macOS does not have such utility out of the box
  local old="${PWD}"

  cd $(dirname "${1}") &&\
  echo "${PWD}/$(basename "${1}")" &&\
  cd "${old}"
}

################################################################################

if (( ${#} != 1 )); then
  cat <<EOT >&2

USAGE: $(basename "${0}") <inp>

<inp> is source MS Office file (docx, xlsx, pptx, etc.)
target directory for unzipped files is <inp>.dir

EOT
  exit 1
fi

################################################################################

set -x

INP=$(realpath "${1}")
DIR="${INP}.dir"

rm -rf "${DIR}"
unzip -d "${DIR}" "${INP}" &&\
exit 0

exit 1

################################################################################
