#!/bin/bash

################################################################################

PRJ="doul"

################################################################################

function exitApp() {
  local ret=${1:0}
  local msg="${2}"

  (( ${ret} != 0 )) && msg="*** ERROR: ${msg:-Build failed}"

  [[ "${msg}" != "" ]] && printf "\n%s\n\n" "${msg}"

  exit ${ret}
}

################################################################################

function realpath() {
    local old="${PWD}"

    cd "${1}" &&\
    echo "${PWD}" &&\
    cd "${old}"
}

################################################################################

TOP=$(dirname "${0}") || exitApp 1 "Failed to determine top directory"
TOP=$(realpath "${TOP}/../") || exitApp 1

OSL=$(uname -s) || exitApp 1 "Failed to retrieve OS kernel name"
OSL=$(echo "${OSL}" | tr [:upper:] [:lower:]) || exitApp 1 "Failed to lowercase OS kernel name"
[[ "${OSL}" == "darwin" ]] && OSL="macos"

SRC="${TOP}/lib"
BIN="${TOP}/bin"
EXE="${BIN}/${OSL}/${PRJ}"

pub get || exitApp 1 "Failed to retrieve packages"
echo "Compiling..."
dart2native "${SRC}/${PRJ}.dart" -o "${EXE}" || exitApp 1 "Failed to compile the executable \"${EXE}\""
chmod 755 "${EXE}" || exitApp 1 "Failed to grant execution permission to the executable file \"${EXE}\""

exitApp 0

################################################################################
