#!/bin/bash

set -Eeo pipefail

################################################################################
# This script should be run from the project's top folder
################################################################################

PRJ="xnx"
VER="0.1.0"

################################################################################

SCRIPT_DIR="$(dirname "${0}")"
cd "$(dirname "${SCRIPT_DIR}")"

TOP="${PWD}"
echo "\nSwitched to the project's top directory: \"${TOP}\""

cd "${TOP}/examples/flutter_app_icons"
echo "Cleaning in: ${PWD}"
rm -rf android ios web

cd "${TOP}/examples/ms_office"
echo "Cleaning in: ${PWD}"
rm -rf out

cd "${TOP}/examples/multi_conf"
echo "Cleaning in: ${PWD}"
rm -rf out

cd "${TOP}/examples/multi_icon"
echo "Cleaning in: ${PWD}"
rm -rf png

cd "${TOP}/examples/site_env"
echo "Deleting: ${PWD}"
rm -rf ReleaseFiles

cd "${TOP}/examples/web_config"
echo "Deleting: ${PWD}"
rm -rf out

echo ""
echo "Completed"

################################################################################
