#!/bin/bash

set -Eeo pipefail

################################################################################

SCRIPT="${0}"
SCRIPT_DIR="$(dirname "${SCRIPT}")"
SCRIPT_NAME="$(basename "${SCRIPT}")"

################################################################################

[[ ${#} < 5 ]] && printf "\nUsage: ${SCRIPT_NAME} <prj> <ver> <arc> <dtl> <pkg-dir>]\n\n" && exit 1

PRJ="${1}"
VER="${2}"
ARC="${3}"
DTL="${4}"
PKG="${5}"

################################################################################

echo "Running ${SCRIPT_NAME}"

echo "Creating and compressing the application package"
"bin/xnx" --move --pack "${PKG}" "${PKG}.tar.gz"

################################################################################
