name: Doul

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest # [ ubuntu-latest, windows-latest, macos-latest ]

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    ##container:
    ##  image:  google/dart:beta

    steps:
      - uses: actions/checkout@v2

      - name: Install Icnsutils on Linux
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install icnsutils

      - name: Install Dart SDK on Linux and macOS
        if: runner.os != 'windows'
        run: |
          brew install dart-lang/dart/dart-beta

      - name: Install Dart SDK on Windows
        if: runner.os == 'windows'
        run: |
          choco install dart-sdk --pre
          refreshenv
          echo %PATH%
          dir C:\tools

      - name: Post-Install Dart SDK on Linux
        if: runner.os == 'linux'
        run: |
          sudo apt-get update

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      ##- name: Run tests
      ##  run: dart test

      # Compilation
      - name: Compile to native
        run: dart2native bin/main.dart -o bin/linux/doul

      # Icons
      - name: Create application icons on Linux
        if: runner.os == 'linux'
        run: bin/linux/doul -d scripts/mkicons
