name: Doul

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # [ ubuntu-latest, windows-latest, macos-latest ]

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    container:
      image:  google/dart:beta

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      ##- name: Run tests
      ##  run: dart test

      # Compilation
      - name: Compile to native
        run: dart2native bin/main.dart -o bin/linux/doul

      # Extra installation
      - name: Installing Chrome 1 of 7
        run: apt-get update; apt-get install -y gettext-base

      - name: Installing Chrome 2 of 7
        run: echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list;

      - name: Installing Chrome 3 of 7
        run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

      - name: Installing Chrome 4 of 7
        run: set -x && apt-get update && apt-get install -y xvfb google-chrome-stable

      - name: Installing Chrome 5 of 7
        run: wget -q -O /usr/bin/xvfb-chrome https://bitbucket.org/atlassian/docker-node-chrome-firefox/raw/ff180e2f16ea8639d4ca4a3abb0017ee23c2836c/scripts/xvfb-chrome

      - name: Installing Chrome 6 of 7
        run: ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome

      - name: Installing Chrome 7 of 7
        run: chmod 755 /usr/bin/google-chrome

      # Icons
      - name: Create application icons
        run: bin/linux/doul -d scripts/mkicons
