name: Xnx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest, windows-latest ]
        #os: [ ubuntu-latest ]
        #os: [ macos-latest ]
        os: [ windows-latest ]

    steps:

      # ################################################################################

      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      ################################################################################

      - name: Installing ImageMagick for Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y imagemagick.app --no-progress
          Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'ImageMagick*')} | %{$_.FullName} | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      ################################################################################

      - name: Installing rsvg-convert for Linux
        if: runner.os == 'Linux'
        run: sudo apt install librsvg2-bin

      - name: Installing rsvg-convert for macOS
        if: runner.os == 'macOS'
        run: brew install librsvg

      - name: Installing rsvg-convert for Windows
        if: runner.os == 'Windows'
        run: choco install -y rsvg-convert --no-progress

      ################################################################################

      - name: Installing dependencies
        run: dart pub get

      ################################################################################

      - name: Analyzing the project source
        run: dart analyze --fatal-infos

      ##############$PSVersionTable##################################################################

      - name: Running unit tests
        run: dart test

      ################################################################################

      - name: Building the application for a POSIX-compliant OS
        if: runner.os != 'Windows'
        run: scripts/build "${{runner.os}}"

      - name: Building the application for Windows
        if: runner.os == 'Windows'
        run: |
          echo COMSPEC=%COMSPEC%
          echo PATH=%PATH%
          cmd /c dir
          scripts\build

      ################################################################################

      - name: Running Integration Test 1 - flutter_app_icons
        run: |
          bin/${{runner.os}}/xnx -d examples/flutter_app_icons
          scripts/Check-Count.ps1 -Expected 40 -Recurse -Path "examples/flutter_app_icons" -Include "*.png"
          bin/${{runner.os}}/xnx -d examples/flutter_app_icons --remove andriod ios web

      ################################################################################

      - name: Running Integration Test 2 - ms_office
        run: |
          bin/${{runner.os}}/xnx -d examples/ms_office
          scripts/Check-Count.ps1 -Expected 12 -Path "examples/ms_office/out"
          bin/${{runner.os}}/xnx -d examples/ms_office --remove out

      ################################################################################

      - name: Running Integration Test 3 - multi_conf
        run: |
          bin/${{runner.os}}/xnx -d examples/multi_conf
          scripts/Check-Count.ps1 -Expected 6 -Path "examples/multi_conf/out"
          bin/${{runner.os}}/xnx -d examples/multi_conf --remove out

      ################################################################################

      - name: Running Integration Test 4 - multi_icon
        run: |
          bin/${{runner.os}}/xnx -d examples/multi_icon
          scripts/Check-Count.ps1 -Expected 12 -Path "examples/multi_icon/png"
          bin/${{runner.os}}/xnx -d examples/multi_icon --remove png

      ################################################################################

      - name: Running Integration Test 5 - setver_azx
        run: |
          bin/${{runner.os}}/xnx -d examples/setver_azx "0.1.45"
          scripts/Check-Count.ps1 -Expected 4 -Pattern '"version": "0.1.45"' -Path "examples/setver_azx/*.json"
          scripts/Check-Count.ps1 -Expected 3 -Pattern '"Major": 0,|"Minor": 1,|"Patch": 45' -Path "examples/setver_azx/task.json"
          bin/${{runner.os}}/xnx -d examples/setver_azx "0.1.44"

      ################################################################################

      - name: Running Integration Test 6 - site_env
        run: |
          bin/${{runner.os}}/xnx -d examples/site_env
          scripts/Check-Count.ps1 -Expected 64 -Recurse -Path "examples/site_env/ReleaseFiles" -Include "*.txt"
          bin/${{runner.os}}/xnx -d examples/site_env --remove ReleaseFiles

      ################################################################################

      - name: Running Integration Test 7 - web_config
        run: |
          bin/${{runner.os}}/xnx -d examples/web_config -x xnx/appconfig.xnx Web.X.config Dev Local=service,eighth
          scripts/Check-Count.ps1 -Expected 1 -Recurse -Path "examples/web_config/out"
          scripts/Check-Count.ps1 -Expected 2 -Recurse -Path "examples/web_config/out/Web.config" -Pattern "localhost"
          scripts/Check-Count.ps1 -Expected 5 -Recurse -Path "examples/web_config/out/Web.config" -Pattern "\.au"
          bin/${{runner.os}}/xnx -d examples/web_config --remove out

      ################################################################################

      - name: Pushing the new binary to the version control
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Pushing the new binary back to the version control'
          add: 'bin/${{runner.os}}/* --force'

      ################################################################################

      - name: Pushing the new application package back to the version control
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Pushing the new application package back to the version control'
          add: 'app/${{runner.os}}/* --force'

      ################################################################################
