name: Xnx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        #os: [ windows-latest ]

    steps:

      ################################################################################

      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - uses: dart-lang/setup-dart@v1

      ################################################################################

      - name: Installing ImageMagick for Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y imagemagick.app --no-progress
          Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'ImageMagick*')} | %{$_.FullName} | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      ################################################################################

      - name: Installing dependencies
        run: dart pub get

      ################################################################################

      - name: Analyzing the project source
        run: dart analyze --fatal-infos

      ##############$PSVersionTable##################################################################

      - name: Running unit tests
        run: dart test

      ################################################################################

      - name: Building the application for a POSIX-compliant OS
        if: runner.os != 'Windows'
        run: scripts/build -o "${{runner.os}}"

      - name: Building the application for Windows
        if: runner.os == 'Windows'
        run: scripts\build

      # ################################################################################

      # - name: Running Integration Test 1 - flutter_app_icons
      #   run: bin/${{runner.os}}/xnx -d examples/flutter_app_icons

      # ################################################################################

      # - name: Running Integration Test 2 - ms_office
      #   run: bin/${{runner.os}}/xnx -d examples/ms_office

      # ################################################################################

      # - name: Running Integration Test 3 - multi_conf
      #   run: bin/${{runner.os}}/xnx -d examples/multi_conf

      # ################################################################################

      # - name: Running Integration Test 4 - multi_icon
      #   run: bin/${{runner.os}}/xnx -d examples/multi_icon

      ################################################################################

      - name: Pushing the new binary to the version control
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Pushing the new binary back to the version control'
          add: 'bin/${{runner.os}}/* --force'

      ################################################################################

      - name: Pushing the new application package back to the version control
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Pushing the new application package back to the version control'
          add: 'app/${{runner.os}}/* --force'

      ################################################################################
